services:
  apigateway:
    build:
      context: .
      dockerfile: MaClasse.ApiGateway/Dockerfile
    container_name: maclasse_apigateway
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:7261
    volumes:
      - "./dataprotection_keys_prod:/app/keys" 
    networks:
        - maclasse_network
    labels:
        - "traefik.enable=true"

  client:
    depends_on:
      - oauth
      - apigateway
      - database
    build:
      context: .
      dockerfile: MaClasse.Client/Dockerfile
    container_name: maclasse_client
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:7235
      - ApiGatewayBaseUrl=https://maclasse.punkydev.fr
    volumes:
      - "./dataprotection_keys_prod:/app/keys"
    networks:
        - maclasse_network
    labels:
        - "traefik.enable=true"
        - "traefik.docker.network=maclasse_network"
        - "traefik.http.routers.maclasse-client-prod.rule=Host(`maclasse.punkydev.fr`)"
        - "traefik.http.routers.maclasse-client-prod.entrypoints=websecure"
        - "traefik.http.routers.maclasse-client-prod.tls.certresolver=myresolver"
        - "traefik.http.services.maclasse-client-prod-svc.loadbalancer.server.port=7235"


  database:
    build:
      context: .
      dockerfile: Service.Database/Dockerfile
    container_name: maclasse_client
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:7012
    volumes:
      - "./dataprotection_keys_prod:/app/keys"
    networks:
      - maclasse_network
    labels:
      - "traefik.enable=true"


  oauth:
    build:
      context: .
      dockerfile: Service.OAuth/Dockerfile
    container_name: maclasse_client
    restart: unless-stopped

    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:7011
    volumes:
      - "./dataprotection_keys_prod:/app/keys"
    networks:
      - maclasse_network
    labels:
      - "traefik.enable=true"
        
networks:
  maclasse_network:
    driver: bridge
    name: maclasse_network 