name: Build and Push Changed Docker Services

on:
  push:
    branches: [main]
    paths:
      - 'MaClasse.ApiGateway/**'
      - 'MaClasse.Client/**'
      - 'Service.Database/**'
      - 'Service.OAuth/**'
      - 'docker-compose.yml'
      - '**/Dockerfile'
      - '**/*.cs'

build-push:
  needs: detect-changes
  runs-on: ubuntu-latest
  strategy:
    matrix:
      include:
        - name: apigateway
          path: MaClasse.ApiGateway
        - name: client
          path: MaClasse.Client
        - name: database
          path: Service.Database
        - name: oauth
          path: Service.OAuth

  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Skip if not changed
      if: needs.detect-changes.outputs[matrix.name] != 'true'
      run: echo "No changes in ${{ matrix.name }}, skipping."

    - name: Build and push Docker image
      if: needs.detect-changes.outputs[matrix.name] == 'true'
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ matrix.name }}:latest
        docker build -t $IMAGE_NAME ./${{ matrix.path }}
        docker push $IMAGE_NAME
