name: Build and Push Changed Docker Services

on:
  push:
    branches: [main]
    paths:
      - 'MaClasse.ApiGateway/**'
      - 'MaClasse.Client/**'
      - 'Service.Database/**'
      - 'Service.OAuth/**'
      - 'docker-compose.yml'
      - '**/Dockerfile'
      - '**/*.cs'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      apigateway: ${{ steps.filter.outputs.apigateway }}
      client: ${{ steps.filter.outputs.client }}
      database: ${{ steps.filter.outputs.database }}
      oauth: ${{ steps.filter.outputs.oauth }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect changed services
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            apigateway:
              - 'MaClasse.ApiGateway/**'
            client:
              - 'MaClasse.Client/**'
            database:
              - 'Service.Database/**'
            oauth:
              - 'Service.OAuth/**'

  build-push:
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: apigateway
            path: MaClasse.ApiGateway
          - name: client
            path: MaClasse.Client
          - name: database
            path: Service.Database
          - name: oauth
            path: Service.OAuth

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Skip if service not changed
        if: needs.detect-changes.outputs[matrix.name] != 'true'
        run: echo "No changes in ${{ matrix.name }}, skipping build."

      - name: Build and push Docker image
        if: needs.detect-changes.outputs[matrix.name] == 'true'
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ matrix.name }}:latest
          DOCKERFILE=${{ matrix.path }}/Dockerfile
          docker build -t $IMAGE_NAME \
            -f $DOCKERFILE . \
            --build-arg PROJECT_PATH=${{ matrix.path }}
          docker push $IMAGE_NAME
